services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    networks: [ default ]
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    env_file: .env
    restart: unless-stopped
    networks: [ default ]
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ELASTIC_XPACK_SECURITY_ENABLED:-false}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS:-"-Xms512m -Xmx512m"}
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:9200 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:16
    container_name: postgres
    env_file: .env
    restart: unless-stopped
    networks: [ default ]
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  flyway:
    image: flyway/flyway:10-alpine
    container_name: flyway
    networks: [ default ]
    env_file: .env
    command: -url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: redis
    env_file: .env
    restart: unless-stopped
    networks: [ default ]
    user: "0"
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  default:
    driver: bridge
